# Generated by Django 3.1.7 on 2021-04-20 00:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('decision_tree', 'decision_tree'), ('random_forest', 'random_forest'), ('logistic_regression', 'logistic_regression'), ('svm', 'svm'), ('neural_networks', 'neural_networks'), ('naive_bayes', 'naive_bayes'), ('linear_regression', 'linear_regression'), ('svr', 'svr'), ('polynomial_regression', 'polynomial_regression')], max_length=100)),
                ('category', models.CharField(choices=[('regressor', 'Regresión'), ('classifier', 'Clasificación')], max_length=100)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
