# Generated by Django 3.1.7 on 2021-07-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_trainingrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciado'), ('finished', 'finalizado'), ('with_errors', 'with_errors')], default='started', max_length=100),
        ),
    ]
