# Generated by Django 3.1.7 on 2021-07-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_trainingrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
